=== KiriSol/KirixCodeEditor/kirix/default_settings_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",

	"type": "object",

	"properties": {
		"$schema": {
			"type": "string"
		},
		"RESERVED_PATHS": {
			"type": "object",
			"patternProperties": {
				"^.*$": {
					"type": "object",
					"properties": {
						"path": {
							"type": "string"
						},
						"readonly": {
							"type": "boolean"
						}
					},
					"required": ["path", "readonly"],
					"additionalProperties": false
				}
			},
			"required": ["HOME", "settings", "default_settings", "help", "welcome"]
		},
		"user_aliases": {
			"type": "object",
			"patternProperties": {
				"^.*$": {
					"type": "string"
				}
			}
		},
		"plugins": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"search_paths": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"report_successful_download": {
			"type": "boolean"
		},
		"UI": {
			"type": "object",
			"properties": {
				"Editor": {
					"type": "object",
					"properties": {
						"font": {
							"type": "string"
						},
						"font_size": {
							"type": "number",
							"minimum": 1,
							"maximum": 60
						},
						"line_spacing": {
							"type": "number",
							"minimum": 0,
							"maximum": 60
						},
						"tab_size": {
							"type": "number",
							"minimum": 1
						}
					},
					"required": ["font", "font_size", "line_spacing", "tab_size"],
					"additionalProperties": false
				},
				"PushMessage": {
					"type": "object",
					"properties": {
						"font": {
							"type": "string"
						},
						"font_size": {
							"type": "number",
							"minimum": 1,
							"maximum": 60
						},
						"title_font_size": {
							"type": "number",
							"minimum": 1,
							"maximum": 60
						},
						"line_spacing": {
							"type": "number",
							"minimum": 1,
							"maximum": 60
						}
					},
					"required": ["font", "font_size", "title_font_size", "line_spacing"],
					"additionalProperties": false
				},
				"PathInput": {
					"type": "object",
					"properties": {
						"font": {
							"type": "string"
						},
						"font_size": {
							"type": "number",
							"minimum": 1,
							"maximum": 60
						}
					},
					"required": ["font", "font_size"],
					"additionalProperties": false
				},
				"Buttons": {
					"type": "object",
					"properties": {
						"font": {
							"type": "string"
						},
						"font_size": {
							"type": "number",
							"minimum": 1,
							"maximum": 60
						}
					},
					"required": ["font", "font_size"],
					"additionalProperties": false
				}
			},
			"required": ["Editor", "PushMessage", "PathInput", "Buttons"]
		},
		"Themes": {
			"type": "object",
			"patternProperties": {
				"^.*$": {
					"type": "object",
					"patternProperties": {
						"^(background|foreground|cursor|selection)$": {
							"type": ["string", "array"],
							"if": { "type": "array" },
							"then": {
								"maxItems": 4,
								"minItems": 3,
								"items": {
									"type": "number",
									"minimum": 0,
									"maximum": 1
								}
							},
							"else": {
								"pattern": "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$"
							}
						},
						"Buttons": {
							"type": "object",
							"patternProperties": {
								"^(background|text_color)$": {
									"type": ["string", "array"],
									"if": { "type": "array" },
									"then": {
										"maxItems": 4,
										"minItems": 3,
										"items": {
											"type": "number",
											"minimum": 0,
											"maximum": 1
										}
									},
									"else": {
										"pattern": "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$"
									}
								},
								"^(background_normal|background_down)$": {
									"type": "string"
								}
							},
							"required": [
								"background",
								"text_color",
								"background_normal",
								"background_down"
							],
							"additionalProperties": false
						},
						"PushMessage": {
							"type": "object",
							"patternProperties": {
								"^(error|warning|info)$": {
									"type": "object",
									"patternProperties": {
										"^(background|title|separator|foreground)$": {
											"type": ["string", "array"],
											"if": { "type": "array" },
											"then": {
												"maxItems": 4,
												"minItems": 3,
												"items": {
													"type": "number",
													"minimum": 0,
													"maximum": 1
												}
											},
											"else": {
												"pattern": "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$"
											}
										}
									},
									"required": [
										"background",
										"title",
										"separator",
										"foreground"
									],
									"additionalProperties": false
								}
							},
							"required": ["error", "warning", "info"],
							"additionalProperties": false
						}
					},
					"required": [
						"background",
						"foreground",
						"cursor",
						"selection",
						"Buttons",
						"PushMessage"
					],
					"additionalProperties": false
				}
			},
			"required": ["Default"]
		},
		"theme": {
			"type": "string"
		}
	},
	"required": [
		"RESERVED_PATHS",
		"plugins",
		"search_paths",
		"report_successful_download",
		"UI",
		"Themes",
		"theme"
	],
	"additionalProperties": false
}

=== KiriSol/KirixCodeEditor/kirix/default_settings.json
{
	"$schema": "./default_settings_schema.json",

	"RESERVED_PATHS": {
		"HOME": {
			"path": "C:\\Users\\rbhbk\\Dev\\KivyApp\\KirixCode",
			"readonly": false
		},
		"settings": {
			"path": "$HOME/kirix/user_settings.json",
			"readonly": false
		},
		"default_settings": {
			"path": "$HOME/kirix/default_settings.json",
			"readonly": true
		},
		"help": {
			"path": "$HOME/kirix/help.md",
			"readonly": true
		},
		"welcome": {
			"path": "$HOME/kirix/welcome.md",
			"readonly": true
		}
	},

	"plugins": [],

	"search_paths": [
		"/storage/emulated/Fonts",
		"/data/data/org.kirapp.kirixcode/files/resources/fonts",
		"./resources/fonts",
		"C:\\Windows\\Fonts",
		"C:\\Users\\rbhbk\\AppData\\Local\\Microsoft\\Windows\\Fonts"
	],

	"report_successful_download": true,

	"UI": {
		"Editor": {
			"font": "JetBrainsMonoNerdFont-Regular.ttf",
			"font_size": 18,
			"line_spacing": 0,
			"tab_size": 4
		},
		"PushMessage": {
			"font": "JetBrainsMonoNerdFont-Regular.ttf",
			"font_size": 15,
			"title_font_size": 13,
			"line_spacing": 1
		},
		"PathInput": {
			"font": "JetBrainsMonoNerdFont-Regular.ttf",
			"font_size": 18
		},
		"Buttons": {
			"font": "JetBrainsMonoNerdFont-Regular.ttf",
			"font_size": 16
		}
	},

	"Themes": {
		"Default": {
			"background": "#C9C0DB",
			"foreground": "#313338",
			"cursor": "#B84B10",
			"selection": "#2EA6D37F",

			"Buttons": {
				"background": "#FFC2E6FF",
				"text_color": "#FFFFFFFF",
				"background_normal": "atlas://data/images/defaulttheme/button",
				"background_down": "atlas://data/images/defaulttheme/button_pressed"
			},
			"PushMessage": {
				"error": {
					"title": "#FC4E41",
					"background": "#FC4E41",
					"separator": "#FC4E41",
					"foreground": "#C9C0DB"
				},
				"warning": {
					"title": "#E4CF6A",
					"background": "#E4CF6A",
					"separator": "#E4CF6A",
					"foreground": "#C9C0DB"
				},
				"info": {
					"title": "#C9C0DB",
					"background": "#5DCFFF",
					"separator": "#5DCFFF",
					"foreground": "#C9C0DB"
				}
			}
		}
	},
	"theme": "Default"
}
